spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schedulerdb
    username: scheduler
    password: scheduler
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

# DO NOT COMMIT CREDENTIALS, USE ONLY LOCALLY

oauth:
  callback-url: your-callback-url

twitter:
  consumer-key: your-consumer-key-here
  consumer-secret: your-consumer-secret-here

facebook:
  app-id: your-app-id
  app-secret: your-app-secret
  permissions: pages_manage_posts,pages_show_list,pages_read_engagement

firebase:
  project-id: your-project-id
  config-path: src/main/resources/credentials/serviceAccountKey.json