spring:
  datasource:
    url: jdbc:postgresql://scheduler-postgres:5432/schedulerdb
    username: scheduler
    password: scheduler
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect